# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "cikl-worker"
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Mike Ryan"]
  s.date = "2014-03-19"
  s.description = "Workers/Post-processors for Cikl"
  s.email = "falter@gmail.com"
  s.executables = ["dns_worker.rb", "dns_worker.rb", "dns_worker_control.rb"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    "Gemfile",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "bin/dns_worker.rb",
    "config/config-cikl-worker-dns.yaml",
    "config/environment.rb",
    "config/named.root",
    "config/unbound.conf",
    "lib/cikl/worker/amqp.rb",
    "lib/cikl/worker/base/config.rb",
    "lib/cikl/worker/base/consumer.rb",
    "lib/cikl/worker/base/job.rb",
    "lib/cikl/worker/base/job_builder.rb",
    "lib/cikl/worker/base/job_result.rb",
    "lib/cikl/worker/base/job_result_amqp_producer.rb",
    "lib/cikl/worker/base/job_result_handler.rb",
    "lib/cikl/worker/base/processor.rb",
    "lib/cikl/worker/base/tracker.rb",
    "lib/cikl/worker/dns/config.rb",
    "lib/cikl/worker/dns/job.rb",
    "lib/cikl/worker/dns/job_builder.rb",
    "lib/cikl/worker/dns/job_result.rb",
    "lib/cikl/worker/dns/processor.rb",
    "lib/cikl/worker/dns/resolver.rb",
    "lib/cikl/worker/logging.rb",
    "spec/logging_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/justfalter/cikl-worker"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "2.0.14"
  s.summary = "Workers/Post-processors for Cikl"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<bunny>, [">= 0"])
      s.add_runtime_dependency(%q<unbound>, ["~> 2.0.0"])
      s.add_runtime_dependency(%q<configliere>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<bunny>, [">= 0"])
      s.add_dependency(%q<unbound>, ["~> 2.0.0"])
      s.add_dependency(%q<configliere>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<bunny>, [">= 0"])
    s.add_dependency(%q<unbound>, ["~> 2.0.0"])
    s.add_dependency(%q<configliere>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

