forge "http://forge.puppetlabs.com"

mod 'puppetlabs/stdlib'
mod 'puppetlabs/apt', '1.4.2'
mod 'elasticsearch/elasticsearch', '0.3.0'
mod 'elasticsearch/logstash', '0.4.3'
mod 'stahnma/epel', '0.0.6'
mod 'example42/perl', '2.0.16'
mod 'nanliu/staging', '0.4.0'
