
name    'jlbfalcao-jruby'
version '1.7.11'
source 'git@github.com:intelie/puppet-jruby.git'
author 'Intelie'
license 'Apache License, Version 2.0'
summary 'JRuby puppet module'
description 'Jruby Puppet instalation'
project_page 'https://github.com/intelie/puppet-jruby'
