#!/usr/bin/env ruby
#^syntax detection
# encoding: utf-8

Vagrant.configure("2") do |config|

  config.vm.box = "Puppetlabs CentOS 6.4 x86_64, VBox 4.2.10"
  config.vm.box_url = "http://puppet-vagrant-boxes.puppetlabs.com/centos-64-x64-vbox4210.box"

  config.vm.provision "shell", inline: %{puppet apply --debug  --execute "class{'jruby': }"}
  
  config.ssh.forward_agent = true
  config.vm.synced_folder ".", "/usr/share/puppet/modules/jruby"
end
