TRUNCATE  archive,
          archive_lookup,
          archive_guid_map,
          hash,
          domain,
          infrastructure,
          url,
          email,
          malware,
          search,
          feed;
