TRUNCATE  archive,
          archive_guid_map,
          hash,
          domain,
          infrastructure,
          url,
          email,
          malware,
          search,
          feed,
          archive_asn,
          archive_cidr,
          archive_email,
          archive_fqdn,
          archive_ip,
          archive_url;
