source "https://rubygems.org"

gem 'bundler', '>= 1.0'
gem 'rake'

gem 'cikl-api',                   :path => File.expand_path("../cikl-api", __FILE__),                 :require => false
gem 'cikl-event',                 :path => File.expand_path("../cikl-event", __FILE__),               :require => false
gem 'cikl-worker',                :path => File.expand_path("../cikl-worker", __FILE__),              :require => false
gem 'threatinator-output-cikl',   :path => File.expand_path("../threatinator-output-cikl", __FILE__), :require => false

