source "https://rubygems.org"

gem 'bundler', '>= 1.0'

gem 'bunny', ">= 1.2.0", :group => [:threatinator, :worker]
gem 'multi_json', ">= 1.10.0", :group => [:threatinator, :worker, :api]
gem 'virtus', ">= 1.0.0", :group => [:event, :api]
gem 'equalizer', ">= 0.0.0", :group => :event

if defined?(JRUBY_VERSION)
  gem 'jrjackson', ">= 0", :group => [:threatinator, :worker, :api]
else
  gem 'oj', ">= 2.9.0", :group => [:threatinator, :worker, :api]
end

# worker
group :worker do
  gem 'unbound', "~> 2.0.0"
  gem 'configliere', "~> 0.4.0"
end

group :api do
  gem 'puma', ">= 2.8.2"
  gem 'elasticsearch', "~> 1.0.0"
  gem 'connection_pool', "~> 2.0.0"
  gem 'jbuilder', ">= 2.0.0"
  gem 'typhoeus', ">= 0.6.8"
  gem 'mongo', "~> 1.10.0"
  gem 'bson_ext', "~> 1.10.0"
  gem 'rack-cors', "~> 0.2.0"
  gem 'grape', "~> 0.7.0"
  gem 'grape-entity', "~> 0.4.0", ">= 0.4.3"
  gem 'grape-swagger', "~> 0.7.0"
end

group :threatinator do
  gem 'threatinator', ">= 0.1.2", :group => :threatinator
end

group :development do
  gem 'rake', ">= 10.0"
  gem 'rspec', ">= 3.0.0"
  ## Worker:
  # gem 'rspec', "< 2.99.0"
  gem 'simplecov', "~> 0.8.0"

  # Threatinator
  gem 'factory_girl', "~> 4.0"


  # API
  gem 'rspec-its', ">= 1.0.0"
  gem 'rack-test', ">= 0.6.2"
  gem 'elasticsearch-extensions', ">= 0.0.15"
  gem 'fabrication', "~> 2.11.0"
  gem 'timecop', "~> 0.7.0"
end
