source "https://rubygems.org"

gemspec name: 'cikl'

group :development do
  gem 'rake', ">= 10.0"
  gem 'rspec', ">= 3.0.0"
  ## Worker:
  # gem 'rspec', "< 2.99.0"
  gem 'simplecov', "~> 0.8.0"

  # Threatinator
  gem 'factory_girl', "~> 4.0"
  gem 'threatinator', '>= 0.1.5'


  # API
  gem 'rspec-its', ">= 1.0.0"
  gem 'rack-test', ">= 0.6.2"
  gem 'elasticsearch-extensions', ">= 0.0.15"
  gem 'fabrication', "~> 2.11.0"
  gem 'timecop', "~> 0.7.0"
end
