require 'pathname'

subprojects = %w| cikl-api cikl-event cikl-worker threatinator-output-cikl |
__current__ = Pathname( File.expand_path('..', __FILE__) )

task :subprojects do
  puts '-'*80
  subprojects.each do |project|
    commit = `git log --pretty=format:'%h %ar: %s' -1 -- #{project}`
    version =  Gem::Specification::load(__current__.join(project, "#{project}.gemspec").to_s).version.to_s
    puts "[#{version}] \e[1m#{project.ljust(subprojects.map {|s| s.length}.max)}\e[0m | #{commit[ 0..80]}..."
  end
end

def setup_coverage(project)
  if ENV['COVERAGE_ROOT']
    puts "COVERAGE_ROOT=#{ENV['COVERAGE_ROOT']}"
    ENV['COVERAGE_DIR'] = File.join(ENV['COVERAGE_ROOT'], project)
  else
    ENV.delete('COVERAGE_DIR')
  end
end

namespace :test do
  desc "Run unit tests in all subprojects"
  task :unit do
    subprojects.each do |project|
      setup_coverage(project)
      puts '-'*80
      sh "cd #{__current__.join(project)} && rake spec:unit"
      puts "\n"
    end
  end

  desc "Run integration tests in all subprojects"
  task :integration do
    subprojects.each do |project|
      setup_coverage(project)
      puts '-'*80
      sh "cd #{__current__.join(project)} && rake spec:integration"
      puts "\n"
    end
  end

  desc "Run all tests in all subprojects"
  task :all do
    subprojects.each do |project|
      setup_coverage(project)
      puts '-'*80
      sh "cd #{__current__.join(project)} && rake spec:all"
      puts "\n"
    end
  end
end
