source "https://rubygems.org"

gemspec

if File.exists? File.expand_path("../../cikl-event/cikl-event.gemspec", __FILE__)
  gem 'cikl-event', :path => File.expand_path("../../cikl-event", __FILE__), :require => false
end

group :test do
  gem 'rake', '>= 10.0'
  gem 'rspec', '~> 3.0'
  gem 'simplecov', '~> 0.8.0'
  gem 'threatinator', '>= 0.1.2'
  gem 'factory_girl', '~> 4.0'
end
