# A sample Gemfile
source "https://rubygems.org"

gem 'grape'
gem 'grape-entity', '>= 0.4.3'
gem 'grape-swagger'
gem 'multi_json'
gem 'rack-cors'
gem 'elasticsearch'
gem 'connection_pool'
gem 'jbuilder'
gem 'typhoeus'
gem 'mongo'
gem 'bson_ext'
gem 'virtus'

gem 'puma'

gem 'oj', :platforms => 'ruby'
gem 'jrjackson', :platforms => 'jruby'

group :development do
  platforms :jruby do
    gem 'warbler'
  end
end

group :test do
  gem 'rake'
  gem 'rspec'
  gem 'rspec-its'
  gem 'rack-test'
  gem 'simplecov'
  gem 'elasticsearch-extensions'
end
